- hosts: localhost
  connection: local
  tasks:
    - name: Creation d'un groupe de ressource
      azure_rm_resourcegroup:
        name: judicael-rg
        location: eastus

    - name: Creation d'un Reseau Virtuel
      azure_rm_virtualnetwork:
        resource_group: judicael-rg
        name: myVnet
        address_prefixes: "10.0.0.0/16"

    - name: Ajout d'un sous-reseau
      azure_rm_subnet:
        resource_group: judicael-rg
        name: mySubnet
        address_prefix: "10.0.1.0/24"
        virtual_network: myVnet

    - name: Creation de l'IP Publique
      azure_rm_publicipaddress:
        resource_group: judicael-rg
        allocation_method: Static
        name: myPublicIP
      register: output_ip_address

    - name: Affichage de l'IP Publique
      debug:
        msg: "The public IP is {{ output_ip_address.state.ip_address }}."

    - name: Creation d'un groupe de securite autorisant SSH
      azure_rm_securitygroup:
        resource_group: judicael-rg
        name: myNetworkSecurityGroup
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound

    - name: Creation d'une interface reseau virtuel
      azure_rm_networkinterface:
        resource_group: judicael-rg
        name: myNIC
        virtual_network: myVnet
        subnet: mySubnet
        ip_configurations:
          - name: "ipconfig"
            public_ip_address_name: myPublicIP
            primary: True
        security_group: myNetworkSecurityGroup

    - name: Creation d'une VM Ubuntu
      azure_rm_virtualmachine:
        resource_group: judicael-rg
        name: myVM
        vm_size: Standard_DS1_v2
        admin_username: ansible
        admin_password: xe3JninMdZGpllJ
        ssh_password_enabled: true
        # ssh_public_keys:
        #   - path: /home/azureuser/.ssh/authorized_keys
        #     key_data: "<key_data>"
        network_interfaces: myNIC
        image:
          offer: 0001-com-ubuntu-server-jammy
          publisher: Canonical
          sku: 22_04-lts
          version: latest
